-- =============================================================================
-- IMS 时区修复迁移：TIMESTAMP -> DATETIME
--
-- 背景：
--   MySQL TIMESTAMP 内部以 UTC 存储，并按"会话时区"做转换。
--   当客户端（如 Navicat）以 UTC 会话连接时，看到的值是 UTC，不是北京时间。
--
-- 修复：
--   把所有时间列改为 DATETIME（按"壁钟时间"原样存储，不做任何时区转换）。
--   配合应用侧 hibernate.jdbc.time_zone=Asia/Shanghai + JVM 默认 Asia/Shanghai，
--   应用读写 Instant 仍然正确，且任何数据库客户端看到的值都是统一的北京时间壁钟值。
--
-- 数据转换：
--   ALTER ... MODIFY 会把已存的 UTC 时刻，按当前 time_zone（+08:00）转成壁钟值写入 DATETIME。
--   因此旧数据"自动"从 UTC 变成北京壁钟时，无需手动 UPDATE。
--
-- 适用：MySQL 8.0+。DATETIME 的 DEFAULT CURRENT_TIMESTAMP / ON UPDATE CURRENT_TIMESTAMP
--      自 5.6.5 起受支持，本环境为 8.0 无问题。
-- =============================================================================

USE inventory_system;

SET time_zone = '+08:00';

-- 1. 认证与权限
ALTER TABLE sys_user
  MODIFY last_login_at DATETIME NULL,
  MODIFY created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sys_role
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sys_user_role
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 2. 基础数据
ALTER TABLE product_category
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE product
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE product_sku
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE warehouse
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE location
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sys_user_warehouse
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE supplier
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE customer
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 3. 出入库单据
ALTER TABLE stock_movement
  MODIFY submitted_at DATETIME NULL,
  MODIFY approved_at  DATETIME NULL,
  MODIFY executed_at  DATETIME NULL,
  MODIFY cancelled_at DATETIME NULL,
  MODIFY created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE stock_movement_item
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 4. 盘点
ALTER TABLE stocktake
  MODIFY snapshot_at  DATETIME NULL,
  MODIFY submitted_at DATETIME NULL,
  MODIFY approved_at  DATETIME NULL,
  MODIFY cancelled_at DATETIME NULL,
  MODIFY created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE stocktake_item
  MODIFY counted_at DATETIME NULL,
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 5. 库存主表 & 变动日志
ALTER TABLE inventory
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE inventory_log
  MODIFY operated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- 6. 安全库存与预警
ALTER TABLE safety_stock_rule
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE stock_alert
  MODIFY handled_at DATETIME NULL,
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 7. 系统
ALTER TABLE sys_audit_log
  MODIFY created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE sys_setting
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sys_idempotency_key
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY expire_at  DATETIME NOT NULL;